import { defineConfig, type Plugins } from "@hey-api/openapi-ts";

/**
 * `additionalProperties: false` as a rejection, not a suggestion.
 *
 * The zod plugin builds every object as `z.object(shape)`, which in Zod *strips*
 * unknown keys instead of refusing them. So `contracts/openapi.yaml` said one
 * thing and the generated validator did another, across the whole API: a reviewer
 * reading `additionalProperties: false` was reading a guarantee that was not in
 * force.
 *
 * `docs/ENGINEERING.md` forbids a hand-written `.strict()` -- that would be a second,
 * competing definition of a schema the contract already owns. This is the
 * generator's own typed resolver hook instead, so the strictness is still
 * generated from the spec and still regenerated by `contracts:generate`.
 *
 * Only the closed case is handled here. Returning `undefined` for everything else
 * runs the plugin's default logic, so `additionalProperties` carrying a real
 * schema still becomes the `z.record(...)` it always did.
 */
const closedObjectsReject: Plugins.Zod.Resolvers["object"] = (ctx) => {
  // Both spellings, because the IR types allow both: the parser turns
  // `additionalProperties: false` into `{ type: "never" }` today, and the literal
  // `false` is still in the type. Matching only the current spelling would fail
  // silently -- generation would succeed and every validator would go back to
  // stripping -- which is the failure this whole change exists to end.
  const additional = ctx.schema.additionalProperties;
  const closed = additional === false || additional?.type === "never";
  if (!closed) return undefined;

  return ctx.$(ctx.symbols.z).attr("strictObject").call(ctx.nodes.shape(ctx));
};

// The spec is a pinned copy of the platform repository's contracts/openapi.yaml.
// Update it only by copying a released version across; never hand-edit it here.
export default defineConfig({
  input: "./openapi.yaml",
  output: {
    path: process.env.DARKVIEW_CONTRACTS_OUT ?? "generated",
    postProcess: [],
  },
  plugins: [
    { name: "@hey-api/typescript", enums: "javascript" },
    { name: "zod", exportFromIndex: true, $resolvers: { object: closedObjectsReject } },
  ],
});
